[book]
authors = ["The Rust Project Developers"]
multilingual = false
src = "src"
title = "Unsafe Code Guidelines Reference"

[output.html]
git-repository-url = "https://github.com/rust-lang/unsafe-code-guidelines"
